# Seed 15 Data
name: 'WebQuestions'
data_dir: '../data/WebQ/'
full_data_dir: '../data/WebQ/full_data/'
vectorize_data_dir: '../data/WebQ/vectorize_data/'
split_data_dir: '../data/WebQ/split_data/'
vectorized_split_data_dir: '../data/WebQ/vectorized_split_data/'

train_data: 'train_vec.json'
valid_data: 'valid_vec.json'
test_data: 'test_vec.json'
pre_word2vec: '../data/WebQ/glove_pretrained_300d_w2v.npy'

# Full vocab
vocab_size: 282949
num_ent_types: 17594
num_relations: 1543

num_query_words: 10

# Output
model_file: '../runs/WebQ/bamnet.md'

# Model
query_size: 20 #32
query_markup_size: 1 # Not used
ans_bow_size: 1 # Not used
ans_path_bow_size: 1 # null
ans_type_bow_size: 16 #added 
ans_path_size: 2 #added
ans_ctx_entity_bow_size: 6

vocab_embed_size: 300
hidden_size: 128
o_embed_size: 128
mem_size: 96
word_emb_dropout: 0.3
que_enc_dropout: 0.3
ans_enc_dropout: 0.2
attention: 'add'
num_hops: 2 #1

# Training
learning_rate: 0.001
#batch_size: 2
batch_size: 16
num_epochs: 3
valid_patience: 10
margin: 1

# Testing
test_batch_size: 1
test_margin:
        - 0.7

# Device
no_cuda: False
gpu: 3
